### ISSUE TITLE
JPS + CushyStudio = ❤️ ?

### ISSUE THREAD

**Issue by rvion** [JPS-GER/JPS-ComfyUI-Workflows#1]
Hi there, I'm the creator of https://github.com/rvion/CushyStudio , I've been playing with your awesome workflows, and would love to integrate them deeply with Cushy; could we get in touch ?

(Cushy is pre-release quality, but I'd love to demo what's coming and how your workflow could work in it!)

if you are on discord, you can contact me there: rvion#8546 or there: https://discord.gg/GfAN6hF2ad
if you are on ComfyUI matrix, you can contact me there: @rvion:matrix.org

**Comment by JPS-GER** [comment]
I will contact you on Discord.
