### ISSUE TITLE
newbie comfyui - FileNotFoundError: [Errno 2] No such file or directory: '/media/2TB/ComfyUI/input/_mask-rgb001.png'

### ISSUE THREAD

**Issue by johndpope** [JPS-GER/JPS-ComfyUI-Workflows#3]
everything loads
I can't see which node is responsible for this.

**Comment by JPS-GER** [comment]
It's one of the IP Adapter Mask 1-4 nodes. Just change it to some of your input images - doesn't have to be a mask unless you want to use the red, green or blue input mask options:

![image](https://github.com/JPS-GER/JPS-ComfyUI-Workflows/assets/142158778/00b26294-d19f-4d99-990f-ae8027fe0169)

**Comment by johndpope** [comment]
ok - thanks
