### ISSUE TITLE
Save filename: documentation

### ISSUE THREAD

**Issue by rafstahelin** [JPS-GER/JPS-ComfyUI-Workflows#4]
Loving the Ed but totally unable to save filenames with counter. Could you possibly add a quick doc on how to handle folder location, filename tokens, counter, and if possible, to add workflow group name (say to add to filename which upscale group name or IPA, etc by group name)... that would be rad. Especially if I'm doing i2i and need the base file used. These are functionalities we are all in dire need for. Another part of this but possibly for another feature request is metadata

**Comment by JPS-GER** [comment]
As we have talked about it on Discord I'm closing this. If you have further questions just ask on Discord.
